version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    container_name: Postgress
    env_file:
      - .env
  web:
    build: .
    container_name: FastApiDelivery
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
